directories:
  output: dmg
  buildResources: build
appId: com.mooplan.app
productName: MooPlan
icon: assets/icon.png
asar: true
files:
  - filter:
      - dist/**
      - electron.cjs
      - preload.js
      - assets/**/*
mac:
  icon: assets/icon.icns
  target:
    - target: dmg
      arch:
        - x64
        - arm64
win:
  icon: assets/icon.ico
  target:
    - target: nsis
      arch:
        - x64
        - ia32
electronVersion: 36.4.0
